language: scala
scala:
- 2.12.7
jdk:
- oraclejdk8
before_install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- npm install
- npm install jsdom
- npm install -g json
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm whoami
script:
- sbt clean fullOptJS::webpack
- json -I -f idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json -e
  'delete this.private'
- json -I -f idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json -e
  'this.license="MIT"'
- json -I -f idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json -e
  'this.name="idealingua-js-facade"'
- json -I -f idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json -e
  'this.description="Idealingua parser and typer"'
- json -I -f idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json -e
  "this.version=\"0.1.$TRAVIS_BUILD_NUMBER\""
- cat idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json
- npm publish idealingua-sjs/target/scala-2.12/scalajs-bundler/main
cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.cache/coursier"
  - "$HOME/.m2"
