language: scala
scala:
- 2.12.7
jdk:
- oraclejdk8
env: 
  - TARGET=idealingua-sjs/target/scala-2.12/scalajs-bundler/main/package.json
before_install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- npm install
- npm install jsdom
- npm install -g json
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm whoami
script:
- sbt clean test
- sbt clean fullOptJS::webpack
after_success:
  - json -I -f $TARGET -e 'delete this.private'
  - json -I -f $TARGET -e 'this.license="EULA"'
  - json -I -f $TARGET -e 'this.name="idealingua-js-facade"'
  - json -I -f $TARGET -e 'this.description="Idealingua parser and typer"'
  - json -I -f $TARGET -e "this.version=\"0.1.$TRAVIS_BUILD_NUMBER\""
  - json -I -f $TARGET -e 'this.main="idealingua-sjs-opt.js"'
  - json -I -f $TARGET -e 'this.runkitExample="var idl = require(\"idealingua-js-facade\");\r\nidl.Idealingua.parsePseudoFS({\"idltest\/enums.domain\":\"\\ndomain idltest.enums\\n\\nenum ShortSyntaxEnum = Element1 | Element2\\n    \"});\r\n"'
  - cat $TARGET
  - npm publish idealingua-sjs/target/scala-2.12/scalajs-bundler/main
cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.cache/coursier"
  - "$HOME/.m2"
