language: scala
scala:
  - 2.12.7
jdk:
  - oraclejdk8
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
script:
  - sbt clean test fastOptJS fullOptJS
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
